### ISSUE TITLE
Mettre le nom du site en Paramétre

### ISSUE THREAD

**Issue by cle69** [domcars0/DomoticzVeolia#1]
Bonjour

Merci pour ce très bon script que Je découvre et que je vais utiliser sur Lyon.
Je fais une suggestion, ne serait-il possible de mettre https://www.eau-services.com ou https://agence.eaudugrandlyon.com/ dans le fichier water.inc

**Comment by domcars0** [comment]
OK , merci c'est intégré dans le code.
