### ISSUE TITLE
Plus d'affichage conso avec Domoticz 2023.2

### ISSUE THREAD

**Issue by thyaoo06** [domcars0/DomoticzVeolia#3]
Bonjour, je suis sous Windows et super content de votre plugin mais depuis la 2023.2 mon dispositif Eau Veolia n'affiche plus de donnée.
J'ai installé votre dernier version pour 2023.1, je vois en mode debug que les updates db se font bien et pourtant meme dans Domoticz mon dispositif n'a pas la dernière date de mise à jour exacte.
Auriez vous une idée du pb svp?
Merci d'avance
Thierry

**Comment by domcars0** [comment]
Bonjour,
Avez vous les consos journalières (à J-2) avec la derniere version du script (Veolia apporte des modifs a son site)? Pour les consos horaires vous devez conserver un historique sur 2 jours au minimum. Etes vous sur Veolia Med ou sur Veolia Gd Lyon ?

**Comment by thyaoo06** [comment]
Ok je recheck tout demain , je suis sous windows et Veolia Med, ce qui explique peut-être le pb.
Merci pour votre réponse, je vous recontacterai et bon weekend

**Comment by thyaoo06** [comment]
Bonjour, ca marche de nouveau. En fait c'était ma base Domoticz qui était foireuse depuis la dernière version. Les IDX des matériels et dispositifs récents visible dans l'appli, ne correspondait pas avec la base.... Je ne comprends pas comment l'appli s'en sortait quand même Désolé pour le dérangement et merci, merci pour ce script que j'utilise tous les jours.
Cordialement / Thierry

**Comment by thyaoo06** [comment]
problème clos donc
